### ISSUE TITLE
Long running process (PHP-FPM)?

### ISSUE THREAD

**Issue by Richard87** [abiosoft/caddy-exec#10]
Hi!

Could this module be used to run PHP-FPM in the background?

Can time-limit be set to 0 or -1 for example?

**Comment by abiosoft** [comment]
@Richard87 

Yes, setting timeout to `0` leaves it running indefinitely. Although it is undocumented at the moment.

Something like this should run indefinitely.
```
exec ping google.com {
    startup
    timeout 0
}
```
