### ISSUE TITLE
pass_thru option

### ISSUE THREAD

**Issue by RubixDev** [abiosoft/caddy-exec#15]
I want caddy to run a command for updating an html file every time I access that page. My current `Caddyfile` looks like this::
```
example.com {
  root * /var/www/{host}
  route /stats {
    exec command-to-update-html-file-at /var/www/example.com/stats/index.html
  }
  file_server
}
```

When I access `example.com/stats` the command is executed but caddy responds with `{"status":"success"}`. Only accessing `example.com/stats/index.html` directly shows the generated html.

Is there (or can you add) an option to not respond directly but continue to the `file_server` directive?

**Comment by andrewbrey** [comment]
@abiosoft I don't know why GH didn't auto-close this issue, when you merged #19 , but I believe that you can close this as complete :+1:
