### ISSUE TITLE
Allow specifying a file for command log output

### ISSUE THREAD

**Issue by francislavoie** [abiosoft/caddy-exec#6]
Looks like currently all the logs are sent to `os.Stderr`, I think it would be nice to allow specifying files for `stdout` and `stderr` logs separately, maybe with rolling? Caddy uses https://github.com/natefinch/lumberjack, it might be a good fit here as well.

Could you even directly reuse FileWriter?

https://github.com/caddyserver/caddy/blob/master/modules/logging/filewriter.go

**Comment by abiosoft** [comment]
thanks for this @francislavoie, looks quite handy and I'll look at adding it.

**Comment by abiosoft** [comment]
Now supports all [log output modules](https://caddyserver.com/docs/caddyfile/directives/log#output-modules) and their configs.
