### ISSUE TITLE
undefined: httpcaddyfile.App

### ISSUE THREAD

**Issue by xmapst** [abiosoft/caddy-exec#9]
/go/pkg/mod/github.com/abiosoft/caddy-exec@v0.0.0-20210304195947-67052cc32b0d/caddyfile.go:185:9: undefined: httpcaddyfile.App

**Comment by awoodbeck** [comment]
It looks like [this commit](https://github.com/abiosoft/caddy-exec/commit/1707be8b658a9eb5a533cf33f72395238ad5d0c2) broke the build since they are dependent on changes in Caddy's master branch which aren't yet tagged with a version.

**Comment by awoodbeck** [comment]
You may need to do something like this to temporarily work around the issue, if you build from source:

```
go mod init caddy
go get github.com/abiosoft/caddy-exec@8d34c546e3f0aa43ba803955e7d5dd2bc7bb3780
go get github.com/caddyserver/caddy/v2
...
```
